_role  = player;
//==================================== GANG MENU ======================================================
_role addaction ["Gang Menu","maindialogs.sqf",["gangmenu"],1,false,true,"","player distance rathaus <= 3 and isciv"];
//====================================== BANK ROB =====================================================
_role addaction ["Rob safe","bankrob.sqf", ["ausrauben", safe1],1,false,true,"",'player distance safe1 <= 3 and isciv'];
_role addaction ["Rob safe","bankrob.sqf", ["ausrauben", safe2],1,false,true,"",'player distance safe2 <= 3 and isciv'];
_role addaction ["Rob safe","bankrob.sqf", ["ausrauben", safe3],1,false,true,"",'player distance safe3 <= 3 and isciv'];
//==================================== HOLSTER PISTOL =================================================
_role addaction ["Holster Pistol","noscript.sqf",'["animation", "holsterpistol"] execVM "holsterscript.sqf";',1,false,true,"",'(player hasweapon "m9" or player hasweapon "Colt1911") and !noholster'];
//==================================== HOLSTER RIFLE =================================================
_role addaction ["Holster Rifle","noscript.sqf",'["animation", "holsterrifle"] execVM "holsterscript.sqf";',1,false,true,"",'player hasweapon "Saiga12K" or player hasweapon "Huntingrifle"'];
//===================================== ASSASSINATION =================================================
_role addaction ["Get Assassination job","assassination.sqf",["getajob_assassin"],1,false,true,"","player distance assassin <= 3 and isciv"];
_role addaction ["Escort VIP", "noscript.sqf", "[VIPtarget] join (group player); player groupchat ""escort the VIP to the police base before he is assassinated!"";",1,false,true,"","player distance VIPtarget < 5 and iscop"];
//========================================= HUNTING ===================================================
_role addaction ["Take boar meat","noscript.sqf",'_no = ceil(random 2);if (((call INV_GetOwnWeight) + ("boar" call INV_getitemTypeKg)*_no) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};(nearestobjects [getpos player, ["wildboar"],  3] select 0) setvariable ["inuse", 1, true]; player playmove "AinvPknlMstpSlayWrflDnon_medic";sleep 4;waituntil {animationstate player != "AinvPknlMstpSlayWrflDnon_medic"};deletevehicle (nearestobjects [getpos player, ["wildboar"],  3] select 0);["boar", _no] call INV_AddInventoryItem;player groupchat format["you got %1 boar meat", _no];',1,true,true,"",'_w = (nearestobjects [getpos player, ["wildboar"],  3] select 0) getvariable "inuse"; isnil "_w" and player distance (nearestobjects [getpos player, ["wildboar"],  3] select 0) < 5 and !alive (nearestobjects [getpos player, ["wildboar"],  3] select 0) and isciv'];
_role addaction ["Take rabbit meat","noscript.sqf",'_no = ceil(random 2);if (((call INV_GetOwnWeight) + ("rabbit" call INV_getitemTypeKg)*_no) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};(nearestobjects [getpos player, ["rabbit"],  3] select 0) setvariable ["inuse", 1, true]; player playmove "AinvPknlMstpSlayWrflDnon_medic";sleep 4;waituntil {animationstate player != "AinvPknlMstpSlayWrflDnon_medic"};deletevehicle (nearestobjects [getpos player, ["rabbit"],  3] select 0);["rabbit", _no] call INV_AddInventoryItem;player groupchat format["you got %1 rabbit meat", _no];',1,true,true,"",'_w = (nearestobjects [getpos player, ["rabbit"],  3] select 0) getvariable "inuse"; isnil "_w" and player distance (nearestobjects [getpos player, ["rabbit"],  3] select 0) < 5 and !alive (nearestobjects [getpos player, ["rabbit"],  3] select 0)'];
//===================================== TARGET RESET ==================================================
_role addaction ["Reset targets","noscript.sqf",'{_x animate["terc",0]} foreach (nearestobjects [getpos player, ["TargetEpopup"],  100])',1,true,true,"",'player distance gunshop1 < 5'];
//===================================== IMPOUND AREA ==================================================
_role addaction ["Impound Lot","maindialogs.sqf",["impound"],1,false,true,"","player distance impoundbuy <= 5"];
_role addaction ["Impound Lot","maindialogs.sqf",["impound"],1,false,true,"","player distance copcar <= 5"];
//================================== COP DELETE EVIDENCE ================================================
_role addaction ["Take evidence","noscript.sqf",'player groupchat "evidence removed."; {deletevehicle _x} foreach (nearestobjects [getpos player, ["weaponholder"], 3])',1,true,true,"",'_weps = (nearestobjects [getpos player, ["weaponholder"], 3] select 0); player distance _weps < 5 and iscop'];
//================================== COP SLAVE ACTIONS ================================================
_role addaction ["Who do you work for?","noscript.sqf",'player groupchat format["this slave works for %1.", leader (nearestobjects [getpos player, civslavearray,  3] select 0)]',1,true,true,"",'_slave = (nearestobjects [getpos player, civslavearray, 3] select 0); !(_slave in playerarray) and player distance _slave < 5 and (leader _slave) in playerarray and iscop'];
_role addaction ["Set slave free","noscript.sqf",'_slave = (nearestobjects [getpos player, civslavearray,  3] select 0); _civ = leader _slave; deletevehicle _slave; (format ["[""slave"", %1] spawn Isse_AddCrimeLogEntry; if(!(""being a slaver"" in %1_reason))then{%1_reason = %1_reason + [""being a slaver""]}; %1_wanted = 1; kopfgeld_%1 = kopfgeld_%1 + 20000;", _civ]) call broadcast;player groupchat "the slave has been freed!";',1,true,true,"",'_slave = (nearestobjects [getpos player, civslavearray, 3] select 0); !(_slave in playerarray) and player distance _slave < 5 and (leader _slave) in playerarray and iscop'];
//================================== COP ESCORT ACTIONS ================================================
_role addaction ["Who is your pimp?","noscript.sqf",'player groupchat format["this escort works for %1.", leader (nearestobjects [getpos player, civescortarray,  3] select 0)]',1,true,true,"",'_escort = (nearestobjects [getpos player, civescortarray, 3] select 0); !(_escort in playerarray) and player distance _escort < 5 and (leader _escort) in playerarray and iscop'];
_role addaction ["Set escort free","noscript.sqf",'_escort = (nearestobjects [getpos player, civescortarray,  3] select 0); _civ = leader _escort; deletevehicle _escort; (format ["[""escort"", %1] spawn Isse_AddCrimeLogEntry; if(!(""being a dirty pimp!!"" in %1_reason))then{%1_reason = %1_reason + [""being a dirty pimp!!""]}; %1_wanted = 1; kopfgeld_%1 = kopfgeld_%1 + 20000;", _civ]) call broadcast;player groupchat "the escort has been freed!";',1,true,true,"",'_escort = (nearestobjects [getpos player, civescortarray, 3] select 0); !(_escort in playerarray) and player distance _escort < 5 and (leader _escort) in playerarray and iscop'];
//---------------------------------COP PATROLS ACTIONS--------------------------------------------------
_role addaction ["Get patrol mission","coppatrol.sqf",["start"],1,false,true,"","iscop and player distance copbank <= 4 and !pmissionactive and !patrolwaittime"];
_role addaction ["Cancel patrol mission","coppatrol.sqf",["end"],1,false,true,"","iscop and pmissionactive and player distance copbank <= 4"];
//========================   unflip vehicle     ================================
_role addaction ["Unflip vehicle","unflipvehicle.sqf",["unflip"],1,false,true,"",'_vcl = (nearestobjects [getpos player, ["Air", "Ship", "LandVehicle"], 3] select 0);player distance _vcl < 5 and _vcl in INV_VehicleArray'];
//==================================== OBJECT ACTIONS =================================================
_role addaction ["Remove Searchlight","noscript.sqf",'if (((call INV_GetOwnWeight) + ("searchlight" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [getpos player, ["SearchLight"], 3] select 0);["searchlight", 1] call INV_AddInventoryItem;player groupchat "you picked up a searchlight";',1,true,true,"",'_light = (nearestobjects [getpos player, ["SearchLight"],  3] select 0); !(_light in speedcamarray) and player distance _light < 5 and iscop'];
_role addaction ["Remove Roadblock","noscript.sqf",'if (((call INV_GetOwnWeight) + ("roadblock" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [getpos player, ["Land_CncBlock_Stripes"],  3] select 0);["roadblock", 1] call INV_AddInventoryItem;player groupchat "you picked up a roadblock";',1,true,true,"",'player distance (nearestobjects [getpos player, ["Land_CncBlock_Stripes"],  3] select 0) < 5 and iscop'];
_role addaction ["Remove Spikestrip","noscript.sqf",'if (((call INV_GetOwnWeight) + ("Spikestrip" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [getpos player, ["cl_Spikestrip"],  3] select 0);["cl_Spikestrip", 1] call INV_AddInventoryItem;player groupchat "you picked up a Spikestrip";',1,true,true,"",'player distance (nearestobjects [getpos player, ["cl_Spikestrip"],  3] select 0) < 5 and iscop'];
_role addaction ["Remove Boom Gate Dual","noscript.sqf",'if (((call INV_GetOwnWeight) + ("Recon_RoadBarrier_D_Duel" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [getpos player, ["Recon_RoadBarrier_D_Duel"],  3] select 0);["Recon_RoadBarrier_D_Duel", 1] call INV_AddInventoryItem;player groupchat "you picked up a Boom gate dual";',1,true,true,"",'player distance (nearestobjects [getpos player, ["Recon_RoadBarrier_D_Duel"],  3] select 0) < 5 and iscop'];
_role addaction ["Remove Boom Gate Single","noscript.sqf",'if (((call INV_GetOwnWeight) + ("Recon_RoadBarrier_D_Single" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [getpos player, ["Recon_RoadBarrier_D_Single"],  3] select 0);["Recon_RoadBarrier_D_Single", 1] call INV_AddInventoryItem;player groupchat "you picked up a Boom gate single";',1,true,true,"",'player distance (nearestobjects [getpos player, ["Recon_RoadBarrier_D_Single"],  3] select 0) < 5 and iscop'];
_role addaction ["Remove Bargate Dual","noscript.sqf",'if (((call INV_GetOwnWeight) + ("Recon_RoadBarrier_Z_Pair" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [getpos player, ["Recon_RoadBarrier_Z_Pair"],  3] select 0);["Recon_RoadBarrier_Z_Pair", 1] call INV_AddInventoryItem;player groupchat "you picked up a bargate dual lane";',1,true,true,"",'player distance (nearestobjects [getpos player, ["Recon_RoadBarrier_Z_Pair"],  3] select 0) < 5 and iscop'];
_role addaction ["Remove Bargate single","noscript.sqf",'if (((call INV_GetOwnWeight) + ("Recon_RoadBarrier_Z_Single" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [getpos player, ["Recon_RoadBarrier_Z_Single"],  3] select 0);["Recon_RoadBarrier_Z_Single", 1] call INV_AddInventoryItem;player groupchat "you picked up a bargate single lane ";',1,true,true,"",'player distance (nearestobjects [getpos player, ["Recon_RoadBarrier_Z_Single"],  3] select 0) < 5 and iscop'];
_role addaction ["Remove Bargate","noscript.sqf",'if (((call INV_GetOwnWeight) + ("Bargate" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [getpos player, ["ZavoraAnim"],  10] select 0);["Bargate", 1] call INV_AddInventoryItem;player groupchat "you picked up a bargate";',1,true,true,"",'player distance (nearestobjects [getpos player, ["ZavoraAnim"],  10] select 0) < 7 and iscop'];
_role addaction ["Harvest Marijuana Plant","noscript.sqf",'if (((call INV_GetOwnWeight) + ("UPMarijuana" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [getpos player, ["Land_MB_Hemp_Tall"],  10] select 0);["UPMarijuana", 1] call INV_AddInventoryItem;player groupchat "You Harvested the Marijuana";',1,true,true,"",'player distance (nearestobjects [getpos player, ["Land_MB_Hemp_Tall"],  10] select 0) < 7 and isciv'];
_role addaction ["Remove Bargate","noscript.sqf",'if (((call INV_GetOwnWeight) + ("Bargate" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [getpos player, ["ZavoraAnim"],  10] select 0);["Bargate", 1] call INV_AddInventoryItem;player groupchat "you picked up a bargate";',1,true,true,"",'player distance (nearestobjects [getpos player, ["ZavoraAnim"],  10] select 0) < 7 and iscop'];
_role addaction ["Open/close gate","noscript.sqf",'_gate = (nearestobjects [getpos player, ["ZavoraAnim"],  10] select 0); if(_gate animationPhase "bargate" == 1)then{_gate animate ["bargate", 0]}else{_gate animate ["bargate", 1]};',1,true,true,"",'player distance (nearestobjects [getpos player, ["ZavoraAnim"],  10] select 0) < 7 and iscop'];
_role addaction ["Remove Fortress","noscript.sqf",'if (((call INV_GetOwnWeight) + ("Fortress" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [getpos player, ["Fortress"],  10] select 0);["Fortress", 1] call INV_AddInventoryItem;player groupchat "you picked up a Fortress";',1,true,true,"",'player distance (nearestobjects [getpos player, ["Fortress"],  10] select 0) < 7 and ("engineer" call INV_HasLicense)'];
_role addaction ["Remove Danger sign","noscript.sqf",'if (((call INV_GetOwnWeight) + ("Sign_Danger" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [getpos player, ["Sign_Danger"],  10] select 0);["Sign_Danger", 1] call INV_AddInventoryItem;player groupchat "you picked up a Danger Sign";',1,true,true,"",'player distance (nearestobjects [getpos player, ["Sign_Danger"],  10] select 0) < 7 and ("engineer" call INV_HasLicense)'];
_role addaction ["Remove Gate","noscript.sqf",'if (((call INV_GetOwnWeight) + ("Land_Wall_Gate_Ind1_L" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [getpos player, ["Land_Wall_Gate_Ind1_L"],  10] select 0);["Land_Wall_Gate_Ind1_L", 1] call INV_AddInventoryItem;player groupchat "you picked up a Gate";',1,true,true,"",'player distance (nearestobjects [getpos player, ["Land_Wall_Gate_Ind1_L"],  10] select 0) < 7 and ("engineer" call INV_HasLicense)'];
_role addaction ["Remove Brick Wall","noscript.sqf",'if (((call INV_GetOwnWeight) + ("Land_Wall_CBrk_5_D" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [getpos player, ["Land_Wall_CBrk_5_D"],  10] select 0);["Land_Wall_CBrk_5_D", 1] call INV_AddInventoryItem;player groupchat "you picked up a Brick Wall";',1,true,true,"",'player distance (nearestobjects [getpos player, ["Land_Wall_CBrk_5_D"],  10] select 0) < 7 and ("engineer" call INV_HasLicense)'];
_role addaction ["Remove Concrete Wall","noscript.sqf",'if (((call INV_GetOwnWeight) + ("Land_Wall_CGry_5_D" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [getpos player, ["Land_Wall_CGry_5_D"],  10] select 0);["Land_Wall_CGry_5_D", 1] call INV_AddInventoryItem;player groupchat "you picked up a Concrete Wall";',1,true,true,"",'player distance (nearestobjects [getpos player, ["Land_Wall_CGry_5_D"],  10] select 0) < 7 and ("engineer" call INV_HasLicense)'];
_role addaction ["Remove Shed","noscript.sqf",'if (((call INV_GetOwnWeight) + ("Land_R_Farm_Cowshed_a" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [getpos player, ["Land_R_Farm_Cowshed_a"],  10] select 0);["Land_R_Farm_Cowshed_a", 1] call INV_AddInventoryItem;player groupchat "you picked up a Shed";',1,true,true,"",'player distance (nearestobjects [getpos player, ["Land_R_Farm_Cowshed_a"],  10] select 0) < 7 and ("engineer" call INV_HasLicense)'];
_role addaction ["Remove Wire","noscript.sqf",'if (((call INV_GetOwnWeight) + ("Fort_RazorWire" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [getpos player, ["Fort_RazorWire"],  10] select 0);["Fort_RazorWire", 1] call INV_AddInventoryItem;player groupchat "you picked up a Wire";',1,true,true,"",'player distance (nearestobjects [getpos player, ["Fort_RazorWire"],  10] select 0) < 7 and iscop'];
_role addaction ["Remove RoadCone","noscript.sqf",'if (((call INV_GetOwnWeight) + ("RoadCone" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [getpos player, ["RoadCone"],  10] select 0);["RoadCone", 1] call INV_AddInventoryItem;player groupchat "you picked up a RoadCone";',1,true,true,"",'player distance (nearestobjects [getpos player, ["RoadCone"],  10] select 0) < 7 and ("engineer" call INV_HasLicense)'];
_role addaction ["Remove Camp Fire","noscript.sqf",'if (((call INV_GetOwnWeight) + ("Land_Campfire" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [getpos player, ["Land_Campfire"],  10] select 0);["Land_Campfire", 1] call INV_AddInventoryItem;player groupchat "you picked up a Camp Fire";',1,true,true,"",'player distance (nearestobjects [getpos player, ["Land_Campfire"],  10] select 0) < 7 and ("engineer" call INV_HasLicense)'];
_role addaction ["Remove Pile Of Wood","noscript.sqf",'if (((call INV_GetOwnWeight) + ("Pile_of_wood" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [getpos player, ["Pile_of_wood"],  10] select 0);["Pile_of_wood", 1] call INV_AddInventoryItem;player groupchat "you picked up a Pile Of Wood";',1,true,true,"",'player distance (nearestobjects [getpos player, ["Pile_of_wood"],  10] select 0) < 7 and ("engineer" call INV_HasLicense)'];
_role addaction ["Remove Fence","noscript.sqf",'if (((call INV_GetOwnWeight) + ("Fence" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [getpos player, ["Fence"],  10] select 0);["Fence", 1] call INV_AddInventoryItem;player groupchat "you picked up a Fence";',1,true,true,"",'player distance (nearestobjects [getpos player, ["Fence"],  10] select 0) < 7 and ("engineer" call INV_HasLicense)'];
_role addaction ["Remove Roadbarrier","noscript.sqf",'if (((call INV_GetOwnWeight) + ("RoadBarrier_long" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [getpos player, ["RoadBarrier_long"],  10] select 0);["RoadBarrier_long", 1] call INV_AddInventoryItem;player groupchat "you picked up a RoadBarrier";',1,true,true,"",'player distance (nearestobjects [getpos player, ["RoadBarrier_long"],  10] select 0) < 7 and ("engineer" call INV_HasLicense)'];
//==================================== REPAIR POWER ===================================================
_role addaction [format["Restore Power 1 ($%1)", powerrestorecost],"noscript.sqf",'_geld = "geld" call INV_GetItemAmount; if(_geld < powerrestorecost)exitwith{player groupchat "you do not have enough money"};["geld", -(powerrestorecost)] call INV_addinventoryitem; "power1 setdamage 0" call broadcast',1,false,true,"","player distance power1 <= 7 and !alive power1 and iscop"];
_role addaction [format["Restore Power 2 ($%1)", powerrestorecost],"noscript.sqf",'_geld = "geld" call INV_GetItemAmount; if(_geld < powerrestorecost)exitwith{player groupchat "you do not have enough money"};["geld", -(powerrestorecost)] call INV_addinventoryitem; "power2 setdamage 0" call broadcast',1,false,true,"","player distance power2 <= 7 and !alive power2 and iscop"];
//================================== COP CHIEF ELECTION ===============================================
_role addaction ["Elect a Chief","maindialogs.sqf",["chief"],1,false,true,"","player distance rathaus <= 3 and iscop"];
//==================================== MAYOR ELECTION =================================================
_role addaction ["Elect a Mayor","maindialogs.sqf",["wahlen"],1,false,true,"","player distance rathaus <= 3"];
//===================================== MAYOR ACTIONS =================================================
_role addaction ["Change the Law","maindialogs.sqf",["gesetz"],1,false,true,"","player distance rathaus <= 3 and isMayor"];
_role addaction ["Change taxes","maindialogs.sqf",["steuern"],1,false,true,"","player distance rathaus <= 3 and isMayor"];
//===================================== CONVOY CASH ===================================================
_role addaction ["Steal Police Payroll","noscript.sqf",'konvoyhascash=false; publicvariable "konvoyhascash"; _cash = (playersNumber west)*20000; ["geld", _cash] call INV_addinventoryitem; player groupchat format["You stole $%1!", _cash];',1,false,true,"","_driver = driver konvoytruck; player distance konvoytruck <= 7 and konvoyhascash and isciv and (!alive _driver or isnull _driver)"];
//===================================== BUY HIDEOUT ===================================================
_role addaction [format["Buy Hideout ($%1)", hideoutcost],"noscript.sqf",'if("geld" call INV_GetItemAmount < hideoutcost)exitwith{player groupchat "not enough money"};["geld", -hideoutcost] call INV_addinventoryitem;["hideout", 1] call INV_addinventoryitem;player groupchat format["you bought a hideout for $%1", hideoutcost];',1,false,true,"","player distance rathaus <= 3 and isciv"];
//===================================== BUY INSURANCE ===================================================
_role addaction [format["Buy bank insurance ($%1)", ("bankversicherung" call INV_getitemBuyCost)],"noscript.sqf",'if("geld" call INV_GetItemAmount < ("bankversicherung" call INV_getitemBuyCost))exitwith{player groupchat "not enough money"};["geld", -("bankversicherung" call INV_getitemBuyCost)] call INV_addinventoryitem;["bankversicherung", 1] call INV_addinventoryitem;player groupchat format["you bought bank insurance for $%1", ("bankversicherung" call INV_getitemBuyCost)];',1,false,true,"","player distance mainbank <= 3"];
//======================================= CRIMELOG ====================================================
_role addaction ["Crime Log","maindialogs.sqf",["coplog"],1,false,true,"","player distance rathaus <= 3"];
//======================================== SLAVES =====================================================
_role addaction [format ["Buy Slave ($%1)", slave_cost],"slaves.sqf", ["slave"],1,false,true,"","player distance slaveflag <= 5 and isciv"];
//==================================== PRIVATE STORAGE ================================================
_role addaction ["Private storage (saved)","storage.sqf",["private_storage", "save"],1,false,true,"","player distance storage < 7"];
//========================================= BAIL ======================================================	 
_role addaction [format ["Pay Bail", slave_cost],"maindialogs.sqf", ["bail"],1,false,true,"","player distance bailflag <= 5 and isciv"];
//====================================== GUN LICENSE ==================================================	 
_role addaction ["Take practical test (probationary license required)","guntest.sqf",["test"],1,false,true,"","player distance Licenseflag2 <= 5 and isciv and !gtactive and !(""semiautomatic"" call INV_HasLicense)"];
_role addaction ["Test info","guntest.sqf",["info"],1,false,true,"","player distance Licenseflag2 <= 5 and isciv"];
//====================================== Drivers LICENSE ==============================================
//_role addaction ["Take Driving test (Learners Drivers license required)","cartest.sqf",["test"],1,false,true,"","player distance Licenseflag3 <= 5 and isciv and !ctactive and !(""car"" call INV_HasLicense)"];
//===================================== ITEM PROCESS ==================================================	 
_role addaction ["Process Oil","itemprocess.sqf",["Oil", "OilBarrel", 50, "oil"],1,false,true,"","player distance Oil_1 <= 5 and isciv"];
_role addaction ["Process Coal","itemprocess.sqf",["Coal", "CleanCoal", 50, "coal"],1,false,true,"","player distance Coal_1 <= 5 and isciv"];
_role addaction ["Process Cocaine","itemprocess.sqf",["Unprocessed_Cocain", "cocaine", 20, "cocaine"],1,false,true,"","player distance cocainelab <= 5 and isciv"];
_role addaction ["Process Wheat","itemprocess.sqf",["getreide", "Bread", 2, "Baker"],1,false,true,"","player distance Bakery_1 <= 5 and isciv"];
_role addaction ["Process Marijuana","itemprocess.sqf",["UPMarijuana", "marihuana", 1, "marijuana"],1,false,true,"","player distance DrugShed <= 5 and isciv"];
//======================================== WORKERS =====================================================
//_role addaction [format ["Buy a worker ($%1)", huren_cost],"worker.sqf", ["holen"],1,false,true,"","(player distance workplace_getjobflag_1 <= 5 or player distance workplace_getjobflag_2 <= 5 or player distance workplace_getjobflag_3 <= 5) and isciv"];		
//======================================= WORKPLACE ====================================================
_role addaction ["Get courier job","delivery.sqf", ["getajob_delivery"],1,false,true,"","(player distance workplace_getjobflag_1 <= 5 or player distance workplace_getjobflag_2 <= 5 or player distance workplace_getjobflag_3 <= 5) and isciv"];		
_role addaction ["Cancel delivery mission","delivery.sqf", ["cancel"],1,false,true,"","(player distance workplace_getjobflag_1 <= 5 or player distance workplace_getjobflag_2 <= 5 or player distance workplace_getjobflag_3 <= 5) and isciv and alreadygotaworkplacejob == 1"];		
_role addaction ["Get taxi job","taxi.sqf", ["getajob_taxi"],1,false,true,"","(player distance workplace_getjobflag_1 <= 5 or player distance workplace_getjobflag_2 <= 5 or player distance workplace_getjobflag_3 <= 5) and isciv"];		
_role addaction ["Finish taxi mission","taxi.sqf", ["canceljob_taxi"],1,false,true,"","(player distance workplace_getjobflag_1 <= 5 or player distance workplace_getjobflag_2 <= 5 or player distance workplace_getjobflag_3 <= 5) and isciv and workplacejob_taxi_active"];	
_role addaction [format [localize "STRS_addAction_buy_shop", (BuyAbleBuildingsArray select 0) select 1, (BuyAbleBuildingsArray select 0) select 3],"buyshop.sqf", ["immobilie", 0],1,false,true,"","player distance ((BuyAbleBuildingsArray select 0) select 2) <= 5 and !(((BuyAbleBuildingsArray select 0) select 0) in BuildingsOwnerArray)"];	
_role addaction [format [localize "STRS_addAction_buy_shop", (BuyAbleBuildingsArray select 1) select 1, (BuyAbleBuildingsArray select 1) select 3],"buyshop.sqf", ["immobilie", 1],1,false,true,"","player distance ((BuyAbleBuildingsArray select 1) select 2) <= 5 and !(((BuyAbleBuildingsArray select 1) select 0) in BuildingsOwnerArray)"];	
_role addaction [format [localize "STRS_addAction_buy_shop", (BuyAbleBuildingsArray select 2) select 1, (BuyAbleBuildingsArray select 2) select 3],"buyshop.sqf", ["immobilie", 2],1,false,true,"","player distance ((BuyAbleBuildingsArray select 2) select 2) <= 5 and !(((BuyAbleBuildingsArray select 2) select 0) in BuildingsOwnerArray)"];
_role addaction [format [localize "STRS_addAction_buy_shop", (BuyAbleBuildingsArray select 3) select 1, (BuyAbleBuildingsArray select 3) select 3],"buyshop.sqf", ["immobilie", 3],1,false,true,"","player distance ((BuyAbleBuildingsArray select 3) select 2) <= 5 and !(((BuyAbleBuildingsArray select 3) select 0) in BuildingsOwnerArray)"];	
_role addaction [format [localize "STRS_addAction_buy_shop", (BuyAbleBuildingsArray select 4) select 1, (BuyAbleBuildingsArray select 4) select 3],"buyshop.sqf", ["immobilie", 4],1,false,true,"","player distance ((BuyAbleBuildingsArray select 4) select 2) <= 5 and !(((BuyAbleBuildingsArray select 4) select 0) in BuildingsOwnerArray)"];	
_role addaction [format [localize "STRS_addAction_buy_shop", (BuyAbleBuildingsArray select 5) select 1, (BuyAbleBuildingsArray select 5) select 3],"buyshop.sqf", ["immobilie", 5],1,false,true,"","player distance ((BuyAbleBuildingsArray select 5) select 2) <= 5 and !(((BuyAbleBuildingsArray select 5) select 0) in BuildingsOwnerArray)"];	
//====================================== VEHICLE ACTIONS ================================================
_role addaction [localize "STRS_addaction_trunk_see","noscript.sqf",'_vcl = (nearestobjects [getpos player, ["Air", "Ship", "LandVehicle"], 3] select 0);_str = format["%1_storage", _vcl];[_str] execVM "vehiclecheck.sqf";',1,true,true,"",'_vcl = (nearestobjects [getpos player, ["Air", "Ship", "LandVehicle"], 3] select 0);player distance _vcl < 5 and !(_vcl in INV_VehicleArray) and _vcl in INV_ServerVclArray and iscop'];
_role addaction [localize "STRS_addaction_trunk_check","noscript.sqf",'_vcl = (nearestobjects [getpos player, ["Air", "Ship", "LandVehicle"], 3] select 0);_str = format["%1_storage", _vcl];if([_vcl,_str] call INV_RemoveIllegalStorage)then{call compile format["publicvariable ""%1"";", _str]};',1,true,true,"",'_vcl = (nearestobjects [getpos player, ["Air", "Ship", "LandVehicle"], 3] select 0);player distance _vcl < 5 and !(_vcl in INV_VehicleArray) and _vcl in INV_ServerVclArray and iscop'];
_role addaction ["Impound vehicle","noscript.sqf",'_vcl = (nearestobjects [getpos player, ["Air", "Ship", "LandVehicle"], 3] select 0);[_vcl, "impound"] execVM "impound.sqf";',1,true,true,"",'_vcl = (nearestobjects [getpos player, ["Air", "Ship", "LandVehicle"], 3] select 0);player distance _vcl < 5 and _vcl in INV_ServerVclArray and iscop'];
_role addaction ["Crush vehicle","noscript.sqf",'_vcl = (nearestobjects [getpos player, ["Air", "Ship", "LandVehicle"], 3] select 0);[_vcl, "crush"] execVM "impound.sqf";',1,true,true,"",'_vcl = (nearestobjects [getpos player, ["Air", "Ship", "LandVehicle"], 3] select 0);player distance _vcl < 5 and _vcl in INV_ServerVclArray and iscop'];
_role addaction ["Pull out","noscript.sqf",'_vcl = (nearestobjects [getpos player, ["Air", "Ship", "LandVehicle"], 3] select 0) execVM "pullout.sqf";',1,true,true,"",'_vcl = (nearestobjects [getpos player, ["Air", "Ship", "LandVehicle"], 3] select 0);player distance _vcl < 5 and count (crew _vcl) > 0 and _vcl in INV_ServerVclArray and iscop'];
_role addaction [localize "STRS_addAction_vehicleinfo","noscript.sqf",'(nearestobjects [getpos player, ["Air", "Ship", "LandVehicle"], 3] select 0) execVM "vehinfo.sqf";',1,true,true,"",'_vcl = (nearestobjects [getpos player, ["Air", "Ship", "LandVehicle"], 3] select 0);player distance _vcl < 5 and _vcl in INV_ServerVclArray'];
_role addaction ["Radio on","noscript.sqf",'(nearestobjects [getpos player, ["Air", "Ship", "LandVehicle"], 3] select 0) _this exec "radio_on.sqs";',1,true,true,"",'_vcl = (nearestobjects [getpos player, ["Air", "Ship", "LandVehicle"], 3] select 0);player in (crew _vcl)'];
_role addaction ["Activate Towing","noscript.sqf",'(nearestobjects [getpos player, ["Air", "Ship", "LandVehicle"], 3] select 0) _this exec "initT.sqs";',1,true,true,"",'_vcl = (nearestobjects [getpos player, ["Air", "Ship", "LandVehicle"], 3] select 0);player in (crew _vcl)'];
//======================================== GANG FLAGS ===================================================
_role addaction ["Capture flag","gangflags.sqf",[gangarea1, "capture"],1,false,true,"",'_control = gangarea1 getvariable "control";player distance gangarea1 <= 10 and isnil "_control" and gangmember and !pickingup'];
_role addaction ["Capture flag","gangflags.sqf",[gangarea2, "capture"],1,false,true,"",'_control = gangarea2 getvariable "control";player distance gangarea2 <= 10 and isnil "_control" and gangmember and !pickingup'];
_role addaction ["Capture flag","gangflags.sqf",[gangarea3, "capture"],1,false,true,"",'_control = gangarea3 getvariable "control";player distance gangarea3 <= 10 and isnil "_control" and gangmember and !pickingup'];
_role addaction ["Capture flag","gangflags.sqf",[gangarea4, "capture"],1,false,true,"",'_control = gangarea4 getvariable "control";player distance gangarea4 <= 10 and isnil "_control" and gangmember and !pickingup'];
_role addaction ["Capture flag","gangflags.sqf",[gangarea5, "capture"],1,false,true,"",'_control = gangarea5 getvariable "control";player distance gangarea5 <= 10 and isnil "_control" and gangmember and !pickingup'];
_role addaction ["Capture flag","gangflags.sqf",[gangarea6, "capture"],1,false,true,"",'_control = gangarea6 getvariable "control";player distance gangarea6 <= 10 and isnil "_control" and gangmember and !pickingup'];
_role addaction ["Neutralise flag","gangflags.sqf",[gangarea1, "neutralise"],1,false,true,"",'_control = gangarea1 getvariable "control";if(isnil "_control")then{_control = ""};player distance gangarea1 <= 6 and _control != (call INV_mygang) and _control != "" and gangmember and !pickingup'];
_role addaction ["Neutralise flag","gangflags.sqf",[gangarea2, "neutralise"],1,false,true,"",'_control = gangarea2 getvariable "control";if(isnil "_control")then{_control = ""};player distance gangarea2 <= 6 and _control != (call INV_mygang) and _control != "" and gangmember and !pickingup'];
_role addaction ["Neutralise flag","gangflags.sqf",[gangarea3, "neutralise"],1,false,true,"",'_control = gangarea3 getvariable "control";if(isnil "_control")then{_control = ""};player distance gangarea3 <= 6 and _control != (call INV_mygang) and _control != "" and gangmember and !pickingup'];
_role addaction ["Neutralise flag","gangflags.sqf",[gangarea4, "neutralise"],1,false,true,"",'_control = gangarea4 getvariable "control";if(isnil "_control")then{_control = ""};player distance gangarea4 <= 6 and _control != (call INV_mygang) and _control != "" and gangmember and !pickingup'];
_role addaction ["Neutralise flag","gangflags.sqf",[gangarea5, "neutralise"],1,false,true,"",'_control = gangarea5 getvariable "control";if(isnil "_control")then{_control = ""};player distance gangarea5 <= 6 and _control != (call INV_mygang) and _control != "" and gangmember and !pickingup'];
_role addaction ["Neutralise flag","gangflags.sqf",[gangarea6, "neutralise"],1,false,true,"",'_control = gangarea6 getvariable "control";if(isnil "_control")then{_control = ""};player distance gangarea6 <= 6 and _control != (call INV_mygang) and _control != "" and gangmember and !pickingup'];

//======================================== SHOP EXPORT ==================================================
_role addaction ["Jan's Place Merchant","shopdialogs.sqf",[4],1,false,true,"","player distance shop1export <= 3"];
_role addaction ["Bagango Merchant","shopdialogs.sqf",[5],1,false,true,"","player distance shop2export <= 3"];
_role addaction ["Mercalillo Merchant","shopdialogs.sqf",[6],1,false,true,"","player distance shop3export <= 3"];
_role addaction ["Dolores Merchant","shopdialogs.sqf",[7],1,false,true,"","player distance shop4export <= 3"];
_role addaction ["Everon Merchant","shopdialogs.sqf",[8],1,false,true,"","player distance shop5export <= 3"];
_role addaction ["Corazol Merchant","shopdialogs.sqf",[9],1,false,true,"","player distance shop6export <= 3"];
_role addaction ["Pita Merchant","shopdialogs.sqf",[10],1,false,true,"","player distance shop7export <= 3"];
_role addaction ["Masbete Merchant","shopdialogs.sqf",[11],1,false,true,"","player distance shop8export <= 3"];
_role addaction ["Eponia Merchant","shopdialogs.sqf",[12],1,false,true,"","player distance shop9export <= 3"];
_role addaction ["Parasio Merchant","shopdialogs.sqf",[13],1,false,true,"","player distance shop10export <= 3"];
_role addaction ["Somato Merchant","shopdialogs.sqf",[14],1,false,true,"","player distance shop11export <= 3"];
_role addaction ["Chantico Merchant","shopdialogs.sqf",[15],1,false,true,"","player distance shop12export <= 3"];
_role addaction ["Cayo Merchant","shopdialogs.sqf",[16],1,false,true,"","player distance shop13export <= 3"];
_role addaction ["Iguana Merchant","shopdialogs.sqf",[17],1,false,true,"","player distance shop14export <= 3"];
_role addaction ["Ortego Merchant","shopdialogs.sqf",[18],1,false,true,"","player distance shop15export <= 3"];


//======================================== SHOP EXPORT ==================================================
//_num1  = (shop1 call INV_getshopnum);
//_num2  = (shop2 call INV_getshopnum);
//_num3  = (shop3 call INV_getshopnum);
//_num4  = (shop4 call INV_getshopnum);
//_role addaction ["Chernogorsk Merchant","shopdialogs.sqf",[_num1],1,false,true,"","player distance shop1export <= 3"];
//_role addaction ["Elektrozavodsk Merchant","shopdialogs.sqf",[_num2],1,false,true,"","player distance shop2export <= 3"];
//_role addaction ["Balota Merchant","shopdialogs.sqf",[_num3],1,false,true,"","player distance shop3export <= 3"];
//_role addaction ["Kamyshovo Merchant","shopdialogs.sqf",[_num4],1,false,true,"","player distance shop4export <= 3"];
//======================================= GANG GUNSHOPS ==================================================
_num1  = (gangarea1 call INV_getshopnum)-3;
_num2  = (gangarea2 call INV_getshopnum)-3;
_num3  = (gangarea3 call INV_getshopnum)-3;
_role addaction ["Gang Shop","shopdialogs.sqf",[_num1],1,false,true,"","_control = gangarea1 getvariable ""control"";!isnil ""_control"" and player distance gangarea1 <= 5 and (_control == (call INV_mygang))"];
_role addaction ["Gang Shop","shopdialogs.sqf",[_num2],1,false,true,"","_control = gangarea2 getvariable ""control"";!isnil ""_control"" and player distance gangarea2 <= 5 and (_control == (call INV_mygang))"];
_role addaction ["Gang Shop","shopdialogs.sqf",[_num3],1,false,true,"","_control = gangarea3 getvariable ""control"";!isnil ""_control"" and player distance gangarea3 <= 5 and (_control == (call INV_mygang))"];

//====================================== DRUG TRAFFICKING ===============================================
_num1  = (gangarea1 call INV_getshopnum);
_num2  = (gangarea2 call INV_getshopnum);
_num3  = (gangarea3 call INV_getshopnum);
_role addaction ["Drug Trafficking","shopdialogs.sqf",[_num1],1,false,true,"","_control = gangarea1 getvariable ""control"";!isnil ""_control"" and player distance gangarea1 <= 5 and isciv"];
_role addaction ["Drug Trafficking","shopdialogs.sqf",[_num2],1,false,true,"","_control = gangarea2 getvariable ""control"";!isnil ""_control"" and player distance gangarea2 <= 5 and isciv"];
_role addaction ["Drug Trafficking","shopdialogs.sqf",[_num3],1,false,true,"","_control = gangarea3 getvariable ""control"";!isnil ""_control"" and player distance gangarea3 <= 5 and isciv"];

//====================================== RED LIGHT ======================================================
_role addaction [format ["Hire escort ($%1)", escort_cost],"escort.sqf", ["escort"],1,false,true,"","player distance redlight1 <= 5 and isciv"];
//===================================== Towing ==================================================	 
//_role addaction ["Tow Vehicle","noscript.sqf",'_vcl = (nearestobjects [getpos player, ["Air", "Ship", "LandVehicle"], 3] select 1);[_this, _vcl] execVM "tow.sqf";',1,true,true,"",'player distance _vcl < 10 and _vcl in INV_ServerVclArray and iscop and player in (crew _this)'];

//_role addaction ["Towing Vehicle","noscript.sqf",'_vcl = (nearestobjects [getpos player, ["Air", "Ship", "LandVehicle"], 3] select 0);["towing",_vcl] execVM "towingselect.sqf";',1,true,true,"",'_vcl = (nearestobjects [getpos player, ["Air", "Ship", "LandVehicle"], 3] select 0);player distance _vcl < 5 and _vcl in INV_ServerVclArray and iscop'];

//_role addaction ["Vehicle to be towed","noscript.sqf",'_vcl = (nearestobjects [getpos player, ["Air", "Ship", "LandVehicle"], 3] select 0);["towed",_vcl] execVM "towingselect.sqf";',1,true,true,"",'_vcl = (nearestobjects [getpos player, ["Air", "Ship", "LandVehicle"], 3] select 0);player distance _vcl < 5 and _vcl in INV_ServerVclArray and iscop'];
